#include "dia.h"

extern uint8_t DIA_VERBOSE_LEVEL;
extern char DIA_VERSION[];
extern char* DIA_CODE_FILE_NAME;
extern FILE* yyout;

dia_node* dia_string(dia_node* arg) {
  DIA_DEBUG("Dia String: %s\n", arg->name);
  return arg;
}

dia_node* dia_integer(dia_node* arg) {
  DIA_DEBUG("Dia Integer: %s\n", arg->name);
  return arg;
}

dia_node* dia_double(dia_node* arg) {
  DIA_DEBUG("Dia Double: %s\n", arg->name);
  return arg;
}


// Predefined functions

void dia_puts() {
  DIA_DEBUG("dia_puts\n");

  fputs("std::cout << ", yyout);

  fputs("std::endl", yyout);
}

void dia_print() {
  DIA_DEBUG("dia_print\n");
}

// The main function

void _dia_comment_generating() {
  DIA_DEBUG("Generating an explanation comment in the main function...\n");

  fputs("/*\n", yyout);
  fputs(" * This code is generated by diac, the Dia programming language compiler.\n", yyout);
  fputs(" * Version Info: ", yyout);
  fputs(DIA_VERSION, yyout);
  fputs("\n", yyout);
  fputs(" *\n", yyout);
  fputs(" * Original Source Code:\n", yyout);
  fputs(" *\n", yyout);
  fputs(" * ```dia\n", yyout);
  fputs(" * ", yyout);

  FILE* source_file = fopen(DIA_CODE_FILE_NAME, "r");
  while(1) {
    char c = fgetc(source_file);
    DIA_DEBUG_2("read byte %02x from the %s file;\n", c, DIA_CODE_FILE_NAME);
    if (c == EOF || c == 0xff) {
      fputs("\n", yyout);
      break;
    }
    else if (c == '\n')
      fputs("\n * ", yyout);
    else
      fputc(c, yyout);
  }
  fclose(source_file);

  fputs(" * ```\n", yyout);
  fputs(" */\n", yyout);
}

void dia_main(dia_node* node) {
  _dia_comment_generating();

  DIA_DEBUG("Generating the main function code...\n");

  fputs("int main(int argc, char** argv) {", yyout);


  fputs("}", yyout);
}
